id = "structurizr"
name = "Structurizr"
version = "0.0.1"
schema_version = 1
authors = ["Rob Hand <146272+sinon@users.noreply.github.com>"]
description = "Local-dev Zed language support scaffold for the Structurizr DSL."
repository = "https://github.com/your-name/zed-structurizr"

[grammars.structurizr]
repository = "file:///Users/rob/dev/tree-sitter-structurizr"
rev = "faa08e5d918baa9bc1a66b425abe87e8cef2f2b5"
