id = "structurizr"
name = "Structurizr DSL for C4 Modelling"
description = "Support for Structurizr used to describe C4 architecture models."
version = "0.0.1"
schema_version = 1
authors = ["Rob Hand <146272+sinon@users.noreply.github.com>"]
repository = "https://github.com/sinon/zed-structurizr"

[grammars.structurizr]
repository = "https://github.com/sinon/tree-sitter-structurizr"
rev = "e2e4dc0f4839e11dca79c8e4c26725744ef6bfdc"
path = "crates/structurizr-grammar"

[language_servers.structurizr-lsp]
name = "Structurizr LSP"
languages = ["Structurizr DSL"]
