id = "structurizr"
name = "Structurizr DSL for C4 Modelling"
description = "Support for Structurizr used to describe C4 architecture models."
version = "0.0.1"
schema_version = 1
authors = ["Rob Hand <146272+sinon@users.noreply.github.com>"]
repository = "https://github.com/sinon/zed-structurizr"

[grammars.structurizr]
repository = "https://github.com/sinon/tree-sitter-structurizr"
rev = "3038d821f68fa30f889c0e0407c4e5b3af29cc84"
path = "crates/strz-grammar"

[language_servers.strz-lsp]
name = "strz LSP for structurizr dsl"
languages = ["Structurizr DSL"]
